spring:
  application:
    name: consumer
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/coupon_example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sorkgkf1!
